### ISSUE TITLE
Version format isn't kept after incrementing

### ISSUE THREAD

**Issue by crqrdotcom** [justjavac/deno-semver#15]
When incrementing a version that has a custom format (i.e. `v0.0.1`), the format isn't kept (i.e. when incrementing `major` the new version is `1.0.0`, without the `v` prefix).

**Actual behavior:**

```ts
const version = new SemVer("v0.0.1");

console.log(version);
// SemVer { raw: "v0.0.1", ... }

version.inc("major");

console.log(version);
// SemVer { raw: "1.0.0", ... }
```

**Expected behavior:**

```ts
const version = new SemVer("v0.0.1");

console.log(version);
// SemVer { raw: "v0.0.1", ... }

version.inc("major");

console.log(version);
// SemVer { raw: "v1.0.0", ... }
```

---

Not sure if the expected behavior for me is intended or not in terms of the scope of this module. Could you confirm, please?

If this is actually a "bug" I can open a PR.

Thanks in advance!

**Comment by justjavac** [comment]
It's not a bug: [Is “v1.2.3” a semantic version?](https://semver.org/#is-v123-a-semantic-version)
